#!/bin/bash
# If don't need to preload OpenCV 2.4 shared objects, you can simply execute it by running ./opencv2-openni
LD_PRELOAD=/usr/local/lib/libopencv_core.so.2.4:/usr/local/lib/libopencv_flann.so.2.4:/usr/local/lib/libopencv_highgui.so.2.4:/usr/local/lib/libopencv_imgproc.so.2.4:/usr/local/lib/libopencv_gpu.so.2.4:/usr/local/lib/libopencv_calib3d.so.2.4:/usr/lib/libcv2.so ./opencv2-openni
